# Creates and pushes release tag, then creates release notes from the changelogs.
# Creates PR to merge changelog and version bump updates from release to main branch
name: Create github tag and PR

on:
  workflow_dispatch:
    inputs:
      tag:
        # Recently published version
        required: true
        description: 'release tag (ie. v2.46.0-rc.0)'
        type: string
        default: 'v2.49.0-rc.0'
      previous-tag:
        # Previous release tag to grab changelogs from
        # To pick the previous tag:
        # - If published tag is the first release candidate, choose the previous full release tag.
        # - If published tag is a subsequent release candidate, choose the previous release candidate.
        # - If published tag is a full release, choose the previous full release tag.
        required: true
        description: 'previous release tag (ie. v2.45.0)'
        type: string
        default: 'v2.48.0'
      create-pr:
        # set to true to create PR to merge changes from release to `main` branch
        required: true
        description: 'Create PR?'
        type: boolean
        default: false

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    if: github.event.inputs.create-pr == 'true'
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          fetch-depth: '0'
      # Create a new branch off the release branch for the PR, we do this to ensure the release branch
      # is not affected
      - name: Create branch
        run: |
          git checkout -b chore/${{ github.event.inputs.tag }}-release
          git push origin chore/${{ github.event.inputs.tag }}-release
      # Create PR with the new branch
      - name: Create Pull Request
        run: |
          gh pr create -B main -H chore/${{ github.event.inputs.tag }}-release --title 'chore(release): ${{ github.event.inputs.tag }}' --body 'Automated release PR for ${{ github.event.inputs.tag }}

            **Checklist**

            - [ ] Verify package version bumps are accurate
            - [ ] Verify CI passes as expected'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-release-tag:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          fetch-depth: '0'
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: https://registry.npmjs.org
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install

      - name: Run changelog script
        id: run-changelog
        run: |
          node ./scripts/get-changelog.js -f ${{ github.event.inputs.previous-tag }} -t ${{ github.event.inputs.tag }} >> changelog.txt

      - name: Read changelog.txt
        id: changelog
        uses: juliangruber/read-file-action@v1
        with:
          path: ./changelog.txt
          trim: true

      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea #v7.0.1
        with:
          script: |
            const changelog = '## `@carbon/ibm-products@2.47.0-rc.0`
              ### Features :rocket:
              - feat(ConditionBuilder): design review changes (#5762)
              - feat(GetStartedCard): update to typescript (#5719)

              ### Bug fixes :bug:
              - fix: datagrid hidden virtual body width (#5798)
              - fix: datagrid sort reset (#5795)
              - fix(PageHeader): correct conditional for non zero offsets (#5791)
              - fix(CreateFullPage): breadcrumb style issue (#5761)
              - fix(Datagrid): only remove single filter for correct table id (#5654)
              - fix(datagrid): screen reader misreads datagrid table headers (#5716)
              - fix: navigation tab usage in story (#5692)
              - fix(Datagrid): editable cell shifting focus to the below cell after edit (#5744)
              - fix(Tearsheet): focus specified els for stacked tearsheets (#5631)

              ### Housekeeping :house:
              - chore(lint-license): add lint checker (#5657)
              - refactor(Card): convert to typescript (#5760)
              - refactor(UserAvatar): convert to typescript (#5771)
              - refactor(action-bar): convert to typescript (#5733)
              - refactor(EmptyState): add types to EmptyState (#5711)
              - chore(storybook): move canary to experimental section (#5645)
              - chore: tagoverflow typescript conversion (#5715)
              - refactor(FullPageError): convert to typescript (#5746)
              - refactor(EmptyStateV2): add typescript types (#5747)

              ## `@carbon/ibm-products-styles@2.43.0-rc.0`
              ### Features :rocket:
              - feat(ConditionBuilder): design review changes (#5762)

              ### Bug fixes :bug:
              - fix(CreateFullPage): breadcrumb style issue (#5761)
              - fix(datagrid): screen reader misreads datagrid table headers (#5716)
              - fix(CreateModal): unnecessary background removed (#5741)

              ### Housekeeping :house:
              - chore(lint-license): add lint checker (#5657)'

            github.rest.repos.createRelease({
              tag_name: '${{ github.event.inputs.tag }}',
              name: '${{ github.event.inputs.tag }}',
              draft: false,
              prerelease: true,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: changelog
            })
