name: Deploy staging (Deploy storybook environment to Github Pages)

on:
  workflow_run:
    workflows: [Minor release]
    types: [completed]
concurrency:
  group: deploy-next-${{ github.ref }}
  cancel-in-progress: true


jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
